- name: Update package cache
  dnf:
    update_cache: yes
    use_backend: dnf4

- name: Install Docker packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    use_backend: dnf4
    state: latest

- name: Start the Docker Service in CentOS
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Adding the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Creating a directory for Dockerfile
  file:
    path: /home/mj/docker_config
    state: directory

- name: Copying the Dockerfile
  copy:
    src: /home/mj/HOA11/files/Dockerfile_CentOS
    dest: /home/mj/docker_config
    owner: mj
    group: mj

- name: Creating volume
  file:
    path: /home/mj/pages
    state: directory

- name: Install required Python library (requests)
  dnf:
    name: python3-requests
    use_backend: dnf4
    state: present

- name: Build Docker image
  command: "docker build -t lamp-userver:1.0 /home/mj/docker_config"

- name: Deploying container
  community.docker.docker_container:
    name: lamp-userver
    image: lamp-userver:1.0
    state: started
    exposed_ports:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - /home/mj/pages:/var/www/html

- block:
  - name: Verify if lamp-userver container is running
    shell: docker ps
    register: container_status

  - debug:
      msg: "{{ container_status }}"

