FROM centos:latest

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# Update the package cache
RUN dnf update -y

# Install HTTPD and MariaDB
RUN dnf install -y httpd mariadb-server

# Start HTTPD and MariaDB
RUN systemctl enable --now httpd mariadb

# Expose port 80 for HTTPD
EXPOSE 80

# Set the working directory
WORKDIR /var/www/html
